# Generated by Django 3.1.1 on 2020-09-18 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name of flow')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name of spec.')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Full name')),
                ('group', models.CharField(max_length=15, verbose_name='Group name')),
                ('attendance', models.IntegerField(default=90, verbose_name='Attendance')),
                ('academic_performance', models.FloatField(default=8, verbose_name='Academic performance')),
                ('date_of_birth', models.DateField(verbose_name='Date of birth.')),
                ('photo', models.ImageField(upload_to='', verbose_name='Avatar')),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.flow')),
                ('specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.specialization')),
            ],
        ),
    ]
