# Generated by Django 3.1.1 on 2020-09-18 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20200918_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description task')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='key',
            field=models.IntegerField(default=3616, primary_key=True, serialize=False, verbose_name='Last 4 number of phone'),
        ),
        migrations.AddField(
            model_name='student',
            name='score',
            field=models.IntegerField(default=0, verbose_name='User Score'),
        ),
    ]
