# Generated by Django 3.1.1 on 2020-09-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_joke'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Joke',
        ),
        migrations.AddField(
            model_name='student',
            name='joke',
            field=models.TextField(blank=True, verbose_name='Joke'),
        ),
    ]
