# Generated by Django 3.1.1 on 2020-09-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_auto_20200918_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hint_4_level',
            field=models.CharField(default='', max_length=500, verbose_name='Hint in 4 level'),
        ),
    ]
