# Generated by Django 3.1.1 on 2020-09-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_student_hint_4_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='level_1',
            field=models.BooleanField(default=False, verbose_name='L1 Done'),
        ),
        migrations.AddField(
            model_name='student',
            name='level_2',
            field=models.BooleanField(default=False, verbose_name='L2 Done'),
        ),
        migrations.AddField(
            model_name='student',
            name='level_3',
            field=models.BooleanField(default=False, verbose_name='L3 Done'),
        ),
        migrations.AddField(
            model_name='student',
            name='level_4',
            field=models.BooleanField(default=False, verbose_name='L4 Done'),
        ),
    ]
