# Generated by Django 3.1.5 on 2021-01-16 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_auto_20200918_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hint_5_level',
            field=models.TextField(default='', max_length=500, verbose_name='Hint in 5 level'),
        ),
        migrations.AddField(
            model_name='student',
            name='hint_6_level',
            field=models.TextField(default='', max_length=500, verbose_name='Hint in 5 level'),
        ),
        migrations.AddField(
            model_name='student',
            name='level_5',
            field=models.BooleanField(default=False, verbose_name='L5 Done'),
        ),
        migrations.AddField(
            model_name='student',
            name='level_6',
            field=models.BooleanField(default=False, verbose_name='L6 Done'),
        ),
    ]
