# Generated by Django 3.1.5 on 2021-01-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_auto_20210116_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='hint_6_level',
            field=models.TextField(default='', max_length=500, verbose_name='Hint in 6 level'),
        ),
    ]
