# Generated by Django 3.1.5 on 2021-01-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_auto_20210117_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='special_data',
            field=models.CharField(blank=True, max_length=100, verbose_name='Special data'),
        ),
    ]
